"""
RAA Earthquake — Multi-Disaster Platform Seed Data
Seeds the database with disaster types, Indian states, glossary terms,
emergency contacts, data sources, safety guides, and historical events.
"""

import json
from datetime import datetime, date


def get_disaster_types():
    """All 34 disaster types with complete data."""
    return [
        {
            "slug": "earthquake", "name": "Earthquake", "icon": "🌍",
            "category": "Geological", "color_code": "#ef4444", "display_order": 1,
            "short_description": "Ground shaking caused by sudden movement along geological faults.",
            "description": "An earthquake is a sudden shaking of the ground caused by the passage of seismic waves through Earth's rocks. Earthquakes occur when energy stored in elastically strained rocks is suddenly released, causing the rocks to break along a fault. The released energy radiates outward from the fault in all directions as seismic waves.",
            "how_it_forms": "Earthquakes are caused by the sudden release of energy in the Earth's lithosphere that creates seismic waves. They are most often caused by geological faults — fractures in the Earth's crust where sections of rock have moved relative to each other. The tectonic plates that make up Earth's outer shell are constantly moving, and friction along plate boundaries causes stress to build up over time. When the stress exceeds the strength of the rocks, they rupture and the stored energy is released as an earthquake.",
            "causes": "Tectonic plate movements, volcanic activity, collapse of underground cavities, and human activities such as mining and reservoir-induced seismicity.",
            "dangers": "Ground shaking, surface rupture, landslides, tsunamis (from undersea earthquakes), liquefaction, building collapse, fires, and aftershocks.",
            "india_relevance": "India is highly seismically active due to the ongoing collision between the Indian Plate and the Eurasian Plate. The Bureau of Indian Standards classifies India into Seismic Zones II through V, with Zone V being the highest risk area covering the Himalayan region, Northeast India, and parts of Gujarat.",
            "common_regions": "Pacific Ring of Fire, Alpide Belt (Mediterranean to Indonesia), Mid-Atlantic Ridge, Himalayan region, East African Rift",
            "frequency_info": "Approximately 500,000 detectable earthquakes occur worldwide each year. About 100,000 are felt and around 100 cause damage.",
            "duration_info": "Ground shaking typically lasts from a few seconds to about a minute for moderate earthquakes, but can last several minutes for great earthquakes (M8.0+)."
        },
        {
            "slug": "tsunami", "name": "Tsunami", "icon": "🌊",
            "category": "Geological/Oceanic", "color_code": "#0ea5e9", "display_order": 2,
            "short_description": "Large ocean waves generated by seafloor displacement from earthquakes, volcanic eruptions, or landslides.",
            "description": "A tsunami is a series of ocean waves with very long wavelengths (typically hundreds of kilometres) caused by large-scale disturbances of the ocean. They are most commonly generated by undersea earthquakes but can also be caused by volcanic eruptions, submarine landslides, and, very rarely, meteorite impacts.",
            "how_it_forms": "When a large earthquake occurs beneath the ocean floor, sections of the seabed may be vertically displaced. This displacement pushes the entire column of water above it, generating waves that travel across the ocean. In deep water, tsunami waves are small (often less than 1 metre) but travel at speeds of 700-900 km/h. As they approach shallow coastal waters, they slow down and their height increases dramatically.",
            "causes": "Undersea earthquakes (most common), volcanic eruptions, submarine landslides, and underwater explosions.",
            "dangers": "Massive coastal flooding, powerful currents, debris impacts, building destruction, and drowning. Multiple waves may arrive over hours.",
            "india_relevance": "India's extensive coastline along the Bay of Bengal, Arabian Sea, and Indian Ocean is vulnerable to tsunamis. The 2004 Indian Ocean tsunami devastated coastal Tamil Nadu, Andaman & Nicobar Islands, and parts of Kerala and Andhra Pradesh. India's tsunami warning system is operated by INCOIS (Indian National Centre for Ocean Information Services).",
            "common_regions": "Pacific Ocean (Ring of Fire), Indian Ocean, Mediterranean Sea, Caribbean Sea",
            "frequency_info": "About two tsunamis per year cause damage. Major destructive tsunamis occur approximately once every 15 years on average.",
            "duration_info": "Tsunami waves can arrive at coastlines anywhere from minutes (near-field) to hours (far-field) after the triggering event. Multiple waves can continue for 12-24 hours."
        },
        {
            "slug": "cyclone", "name": "Cyclone / Tropical Cyclone", "icon": "🌀",
            "category": "Meteorological", "color_code": "#8b5cf6", "display_order": 3,
            "short_description": "Intense rotating storm systems forming over warm tropical oceans with destructive winds, heavy rain, and storm surge.",
            "description": "A tropical cyclone is a rapidly rotating storm system characterized by a low-pressure center, a closed low-level atmospheric circulation, strong winds, and spiral arrangement of thunderstorms that produce heavy rain and storm surge. Depending on the region, they are called hurricanes (Atlantic/East Pacific), typhoons (West Pacific), or cyclones (Indian Ocean/South Pacific).",
            "how_it_forms": "Tropical cyclones form over warm ocean waters (typically above 26.5°C) when atmospheric conditions including low wind shear, sufficient Coriolis force, and high humidity combine. Warm, moist air rises rapidly from the ocean surface, creating an area of low pressure. Surrounding air rushes in, is deflected by Earth's rotation, and begins to spiral. As the warm air rises and cools, it releases energy through condensation, fuelling the storm's intensification.",
            "causes": "Warm ocean surface temperatures, atmospheric instability, sufficient Coriolis effect, low vertical wind shear, and pre-existing weather disturbances.",
            "dangers": "Extreme winds, torrential rainfall, storm surge, coastal flooding, inland flooding, flying debris, and tornadoes within the storm.",
            "india_relevance": "India is highly vulnerable to cyclones from both the Bay of Bengal and the Arabian Sea. The east coast (Odisha, Andhra Pradesh, West Bengal, Tamil Nadu) is particularly affected. Major cyclones include the 1999 Odisha Super Cyclone, Cyclone Fani (2019), Cyclone Amphan (2020), and Cyclone Biparjoy (2023). The India Meteorological Department (IMD) provides cyclone tracking and warnings.",
            "common_regions": "Bay of Bengal, Arabian Sea, Western Pacific, Eastern Pacific, Atlantic Ocean, South Pacific, Southwest Indian Ocean",
            "frequency_info": "About 80-90 tropical cyclones form globally each year. India faces an average of 4-6 cyclones per year in the North Indian Ocean basin.",
            "duration_info": "Cyclones typically last 3-14 days, with the most intense phase lasting 1-5 days."
        },
        {
            "slug": "flood", "name": "Flood", "icon": "🌧️",
            "category": "Hydrological", "color_code": "#3b82f6", "display_order": 4,
            "short_description": "Overflow of water onto normally dry land due to heavy rainfall, river overflow, or dam failure.",
            "description": "A flood is an overflow of water that submerges land that is usually dry. Floods can occur when the volume of water within a body of water, such as a river or lake, exceeds its capacity, causing water to flow beyond the natural or artificial banks.",
            "how_it_forms": "Floods result from excessive water accumulation that overwhelms natural or built drainage systems. Causes include prolonged heavy rainfall, rapid snowmelt, river overflow, coastal storm surge, dam or levee failure, and urban drainage failure.",
            "causes": "Heavy or prolonged rainfall, river overflow, rapid snowmelt, storm surge, dam/levee failure, and inadequate urban drainage.",
            "dangers": "Drowning, property damage, contaminated water supply, disease outbreaks, soil erosion, infrastructure destruction, and displacement.",
            "india_relevance": "India experiences severe flooding almost every year, particularly during the monsoon season (June-September). States like Bihar, Assam, Uttar Pradesh, West Bengal, Kerala, and Maharashtra are regularly affected. The Brahmaputra, Ganges, and other major river systems cause widespread annual flooding. The Central Water Commission (CWC) monitors flood situations.",
            "common_regions": "Monsoon regions of Asia, river floodplains worldwide, coastal areas, low-lying delta regions",
            "frequency_info": "Floods are the most common natural disaster globally. India experiences major flooding events virtually every monsoon season.",
            "duration_info": "Flash floods may last hours, while riverine floods can persist for days to weeks. Urban flooding duration depends on drainage capacity."
        },
        {
            "slug": "flash-flood", "name": "Flash Flood", "icon": "⚡🌊",
            "category": "Hydrological", "color_code": "#2563eb", "display_order": 5,
            "short_description": "Rapid, intense flooding caused by heavy rainfall in a short period, often in hilly or urban areas.",
            "description": "A flash flood is a rapid flooding event that occurs within six hours of heavy rainfall, a dam or levee failure, or the sudden release of water. Flash floods are particularly dangerous because they develop quickly, often with little warning, and can move with tremendous force.",
            "india_relevance": "Flash floods are common in the Himalayan states (Uttarakhand, Himachal Pradesh, Jammu & Kashmir), Northeast India, and Western Ghats regions. The 2013 Uttarakhand disaster was one of India's worst flash flood events.",
            "common_regions": "Mountainous regions, urban areas, narrow valleys, arid regions with sudden rain",
            "frequency_info": "Flash floods occur frequently worldwide, particularly in mountainous and urban areas during intense rainfall events.",
            "duration_info": "Flash floods typically last minutes to hours but can cause catastrophic damage in that short time."
        },
        {
            "slug": "urban-flooding", "name": "Urban Flooding", "icon": "🏙️🌊",
            "category": "Hydrological", "color_code": "#1d4ed8", "display_order": 6,
            "short_description": "Flooding in cities and towns due to overwhelmed drainage systems during heavy rainfall.",
            "description": "Urban flooding occurs when heavy rainfall overwhelms the drainage capacity of cities. Impermeable surfaces like concrete and asphalt prevent water absorption, and inadequate drainage infrastructure causes water to accumulate rapidly on streets and in buildings.",
            "india_relevance": "Indian cities like Mumbai, Chennai, Hyderabad, Bengaluru, and Kolkata regularly experience severe urban flooding during the monsoon. The 2005 Mumbai floods and 2015 Chennai floods were catastrophic examples. Rapid urbanization and encroachment on natural drainage channels worsen the problem.",
            "common_regions": "Major cities in monsoon regions, rapidly urbanizing areas, coastal cities",
            "frequency_info": "Urban flooding is increasingly common globally due to climate change and rapid urbanization.",
            "duration_info": "Urban floods may last from hours to several days depending on rainfall and drainage capacity."
        },
        {
            "slug": "lightning", "name": "Lightning", "icon": "⚡",
            "category": "Meteorological", "color_code": "#eab308", "display_order": 7,
            "short_description": "Sudden electrostatic discharge in the atmosphere during thunderstorms, causing injury and death.",
            "description": "Lightning is a naturally occurring electrostatic discharge during which two electrically charged regions, either both in the atmosphere or with one on the ground, temporarily neutralize themselves, causing the instantaneous release of an average of one gigajoule of energy.",
            "how_it_forms": "Lightning forms through charge separation within cumulonimbus clouds. As ice particles and water droplets collide within the cloud, positive charges accumulate at the top and negative charges at the bottom. When the electrical potential difference becomes large enough, it overcomes the insulating properties of air and a lightning bolt occurs.",
            "india_relevance": "India records one of the highest numbers of lightning-related deaths globally, with over 2,000 deaths reported annually. States like Bihar, Jharkhand, Uttar Pradesh, Madhya Pradesh, and Maharashtra are most affected. Lightning strikes increase during the pre-monsoon (April-June) and monsoon (July-September) seasons.",
            "common_regions": "Tropical and subtropical regions, continental interiors, areas with high thunderstorm frequency",
            "frequency_info": "Approximately 1.4 billion lightning flashes occur worldwide each year — about 40-50 per second.",
            "duration_info": "Individual lightning bolts last only microseconds to milliseconds, but thunderstorms producing lightning can last hours."
        },
        {
            "slug": "thunderstorm", "name": "Thunderstorm", "icon": "⛈️",
            "category": "Meteorological", "color_code": "#a16207", "display_order": 8,
            "short_description": "Storm with lightning, thunder, heavy rain, and sometimes hail or strong winds.",
            "description": "A thunderstorm is a storm characterized by the presence of lightning and thunder, typically producing heavy rain, strong winds, and sometimes hail. Severe thunderstorms can produce tornadoes, damaging winds, and dangerous lightning.",
            "india_relevance": "India experiences frequent thunderstorms, particularly during the pre-monsoon season. Nor'westers (Kal Baisakhi) are violent thunderstorms that affect eastern India, especially West Bengal, Bihar, and Jharkhand.",
            "common_regions": "Tropical and temperate regions worldwide, particularly continental interiors",
            "frequency_info": "About 40,000 thunderstorms occur daily worldwide. India experiences its peak thunderstorm season from March to June.",
            "duration_info": "Individual thunderstorm cells typically last 30 minutes to an hour, but multi-cell storms can persist for hours."
        },
        {
            "slug": "tornado", "name": "Tornado", "icon": "🌪️",
            "category": "Meteorological", "color_code": "#71717a", "display_order": 9,
            "short_description": "Violently rotating column of air extending from a thunderstorm to the ground.",
            "description": "A tornado is a violently rotating column of air that is in contact with both the surface of the Earth and a cumulonimbus cloud. Tornadoes are among the most destructive atmospheric phenomena, with the most intense producing wind speeds exceeding 480 km/h.",
            "india_relevance": "While tornadoes are less common in India than in the United States, they do occur, particularly in the eastern Gangetic plains. Notable Indian tornadoes include the 1998 Tongi tornado in Bangladesh border region and periodic events in Bihar and West Bengal.",
            "common_regions": "Central United States (Tornado Alley), Bangladesh, parts of eastern India, southeastern South America, parts of Europe and Australia",
            "frequency_info": "About 1,000 tornadoes are reported in the United States each year. India experiences fewer but still significant tornado events.",
            "duration_info": "Most tornadoes last less than 10 minutes, though some can persist for over an hour."
        },
        {
            "slug": "extreme-wind", "name": "Extreme Winds", "icon": "💨",
            "category": "Meteorological", "color_code": "#64748b", "display_order": 10,
            "short_description": "Dangerously high winds that can cause structural damage, power outages, and flying debris.",
            "india_relevance": "Extreme winds in India are often associated with cyclones, thunderstorms (especially dust storms and squalls), and the Loo (hot wind) in northern India during summer.",
        },
        {
            "slug": "hailstorm", "name": "Hailstorm", "icon": "🧊",
            "category": "Meteorological", "color_code": "#94a3b8", "display_order": 11,
            "short_description": "Storm producing balls of ice (hail) that can damage crops, vehicles, and buildings.",
            "india_relevance": "Hailstorms occur in India during the pre-monsoon season, particularly in the northern plains, central India, and parts of the Deccan Plateau. They cause significant agricultural damage.",
        },
        {
            "slug": "dust-storm", "name": "Dust Storm", "icon": "🌫️",
            "category": "Meteorological", "color_code": "#b45309", "display_order": 12,
            "short_description": "Strong winds carrying large amounts of sand and dust, reducing visibility and causing health hazards.",
            "india_relevance": "Dust storms (Andhi) are common in Rajasthan, Gujarat, and western Uttar Pradesh during the pre-monsoon season (May-June). They can reduce visibility to near zero and cause significant damage.",
        },
        {
            "slug": "landslide", "name": "Landslide", "icon": "🏔️",
            "category": "Geological", "color_code": "#92400e", "display_order": 13,
            "short_description": "Downslope movement of rock, soil, and debris triggered by rainfall, earthquakes, or human activity.",
            "description": "A landslide is the movement of a mass of rock, debris, or earth down a slope under the influence of gravity. Landslides are triggered by natural events such as heavy rainfall, earthquakes, volcanic activity, and erosion, or by human activities such as deforestation and construction.",
            "india_relevance": "India is highly prone to landslides, particularly in the Himalayas, Northeast India, and Western Ghats. Heavy monsoon rainfall is the primary trigger. The Geological Survey of India (GSI) monitors landslide-prone areas. States most affected include Uttarakhand, Himachal Pradesh, Jammu & Kashmir, Meghalaya, and Kerala.",
            "common_regions": "Mountainous regions worldwide, steep coastal cliffs, volcanic slopes, areas with heavy rainfall",
            "frequency_info": "Thousands of landslides occur in India annually during the monsoon season.",
            "duration_info": "Landslides can occur in seconds (rockfalls) to hours (mudflows) or even develop slowly over months."
        },
        {
            "slug": "avalanche", "name": "Avalanche", "icon": "❄️🏔️",
            "category": "Geological", "color_code": "#bae6fd", "display_order": 14,
            "short_description": "Rapid flow of snow down a mountain slope, burying everything in its path.",
            "description": "An avalanche is a rapid flow of snow down a slope, triggered by natural causes (snowfall, wind, temperature changes) or human activity. Snow avalanches are the primary concern and can reach speeds exceeding 300 km/h.",
            "india_relevance": "Avalanches primarily affect the Himalayan states: Jammu & Kashmir, Himachal Pradesh, Uttarakhand, and Sikkim. The Defence Geoinformatics Research Establishment (DGRE) under DRDO monitors avalanche conditions. Avalanches are a significant hazard for military personnel, mountaineers, and communities in high-altitude areas.",
            "common_regions": "Himalayas, Alps, Rocky Mountains, Andes, and other major mountain ranges",
        },
        {
            "slug": "volcanic-eruption", "name": "Volcanic Eruption", "icon": "🌋",
            "category": "Geological", "color_code": "#dc2626", "display_order": 15,
            "short_description": "Eruption of magma, ash, and gases from a volcano, potentially devastating surrounding areas.",
            "description": "A volcanic eruption occurs when magma from within the Earth's mantle reaches the surface, resulting in the outpouring of lava, ejection of rock fragments and ash, and emission of volcanic gases. Eruptions range from gentle lava flows to catastrophic explosions.",
            "india_relevance": "India has one active volcano: Barren Island in the Andaman Sea, which last erupted in 2017. While volcanic eruptions are not a major direct threat to mainland India, eruptions in Indonesia and other nearby volcanic regions could produce ash clouds or tsunamis affecting Indian coastlines.",
            "common_regions": "Pacific Ring of Fire, Mediterranean, East African Rift, Iceland, Indonesia, Japan",
        },
        {
            "slug": "wildfire", "name": "Wildfire / Forest Fire", "icon": "🔥",
            "category": "Environmental", "color_code": "#ea580c", "display_order": 16,
            "short_description": "Uncontrolled fire in forests, grasslands, or wildland areas, destroying vegetation and threatening communities.",
            "description": "A wildfire is an unplanned, uncontrolled fire burning in natural areas such as forests, grasslands, and prairies. Wildfires can be caused by lightning, human activities, or spontaneous combustion. They can spread rapidly, especially under hot, dry, and windy conditions.",
            "india_relevance": "Forest fires are common in India, particularly in Uttarakhand, Himachal Pradesh, Northeast India, Odisha, Madhya Pradesh, and Chhattisgarh during the dry season (February-June). The Forest Survey of India (FSI) monitors fire incidents using satellite data.",
            "common_regions": "Western United States, Mediterranean region, Australia, Southeast Asia, Amazon, India's forested regions",
        },
        {
            "slug": "drought", "name": "Drought", "icon": "☀️🏜️",
            "category": "Climatological", "color_code": "#ca8a04", "display_order": 17,
            "short_description": "Extended period of abnormally low rainfall leading to water shortage and crop failure.",
            "description": "A drought is a prolonged period of abnormally low rainfall, leading to a shortage of water. Droughts can be meteorological (lack of precipitation), agricultural (soil moisture deficit), hydrological (low water levels in rivers/reservoirs), or socioeconomic (water demand exceeds supply).",
            "india_relevance": "India is highly vulnerable to droughts, particularly in Rajasthan, Maharashtra (Marathwada, Vidarbha), Karnataka, Andhra Pradesh, Telangana, and parts of Tamil Nadu. The Indian Meteorological Department (IMD) monitors drought conditions. Monsoon failure is the primary cause of drought in India.",
            "common_regions": "Sub-Saharan Africa, South Asia, Middle East, Australia, Western United States, Mediterranean",
        },
        {
            "slug": "heatwave", "name": "Heatwave", "icon": "🌡️",
            "category": "Meteorological", "color_code": "#b91c1c", "display_order": 18,
            "short_description": "Prolonged period of excessively hot weather that can cause heat-related illness and death.",
            "description": "A heatwave is a prolonged period of excessively high temperatures, often combined with high humidity, that significantly exceeds the normal maximum temperatures for a given region. Heatwaves are defined differently across regions based on local climate norms.",
            "india_relevance": "India experiences severe heatwaves during March-June, with temperatures exceeding 45°C in many regions. Rajasthan, Gujarat, Madhya Pradesh, Maharashtra, Telangana, Andhra Pradesh, Odisha, Bihar, and Uttar Pradesh are most affected. IMD issues heatwave warnings when temperatures exceed the normal by 4.5-6.4°C or more. Heatwaves cause hundreds of deaths in India annually.",
            "common_regions": "South Asia, Middle East, Mediterranean, Central United States, Australia, East Asia",
        },
        {
            "slug": "cold-wave", "name": "Cold Wave", "icon": "❄️",
            "category": "Meteorological", "color_code": "#1e40af", "display_order": 19,
            "short_description": "Extended period of abnormally cold weather that can cause hypothermia and frost damage.",
            "india_relevance": "Cold waves affect northern India during December-February, particularly Rajasthan, Punjab, Haryana, Uttar Pradesh, Bihar, and Delhi. IMD declares a cold wave when temperatures drop significantly below normal. Cold waves disproportionately affect homeless and vulnerable populations.",
        },
        {
            "slug": "extreme-rainfall", "name": "Extreme Rainfall", "icon": "🌧️⚠️",
            "category": "Meteorological", "color_code": "#4338ca", "display_order": 20,
            "short_description": "Unusually intense or prolonged rainfall exceeding normal levels, leading to flooding and landslides.",
            "india_relevance": "India experiences extreme rainfall events during the monsoon season. Mumbai, Chennai, Kerala, and Northeast India are particularly prone. IMD classifies rainfall as heavy (64.5-115.5 mm/day), very heavy (115.6-204.4 mm/day), and extremely heavy (>204.4 mm/day).",
        },
        {
            "slug": "storm-surge", "name": "Storm Surge", "icon": "🌊💨",
            "category": "Meteorological/Oceanic", "color_code": "#0369a1", "display_order": 21,
            "short_description": "Abnormal rise of sea level during a cyclone, causing devastating coastal flooding.",
            "india_relevance": "Storm surge is a major threat along India's eastern coast during cyclones. The flat coastal topography of West Bengal, Odisha, and Andhra Pradesh makes them particularly vulnerable. The 1970 Bhola cyclone (Bangladesh) and 1999 Odisha super cyclone produced catastrophic storm surges.",
        },
        {
            "slug": "coastal-flooding", "name": "Coastal Flooding", "icon": "🏖️🌊",
            "category": "Hydrological", "color_code": "#0284c7", "display_order": 22,
            "short_description": "Flooding of coastal areas due to storm surge, high tides, or sea level rise.",
            "india_relevance": "India has a 7,516 km coastline with many low-lying areas vulnerable to coastal flooding. Mumbai, Chennai, Kolkata, and many small coastal towns face regular flooding risk from high tides and cyclones.",
        },
        {
            "slug": "cloudburst", "name": "Cloudburst", "icon": "🌧️💥",
            "category": "Meteorological", "color_code": "#6366f1", "display_order": 23,
            "short_description": "Sudden, extreme rainfall over a small area, dumping large amounts of water in minutes.",
            "india_relevance": "Cloudbursts are common in the Himalayan states, particularly Uttarakhand, Himachal Pradesh, and Jammu & Kashmir. They cause flash floods and landslides in narrow valleys. The 2013 Kedarnath disaster was triggered by a cloudburst.",
        },
        {
            "slug": "snowstorm", "name": "Snowstorm / Heavy Snow", "icon": "🌨️",
            "category": "Meteorological", "color_code": "#7dd3fc", "display_order": 24,
            "short_description": "Heavy snowfall with strong winds, reducing visibility and blocking roads.",
            "india_relevance": "Snowstorms affect the Himalayan states during winter months. Jammu & Kashmir, Himachal Pradesh, Uttarakhand, and Sikkim experience heavy snowfall that can isolate communities and disrupt transportation.",
        },
        {
            "slug": "sandstorm", "name": "Sandstorm", "icon": "🏜️💨",
            "category": "Meteorological", "color_code": "#d97706", "display_order": 25,
            "short_description": "Strong wind carrying sand particles, reducing visibility and causing respiratory problems.",
            "india_relevance": "Sandstorms affect Rajasthan and parts of Gujarat, particularly during the pre-monsoon season. The Thar Desert is the primary source region.",
        },
        {
            "slug": "sinkhole", "name": "Sinkhole", "icon": "🕳️",
            "category": "Geological", "color_code": "#78716c", "display_order": 26,
            "short_description": "Sudden collapse of the ground surface creating a hole, caused by dissolution of underlying rock.",
            "india_relevance": "Sinkholes occasionally occur in India, particularly in limestone and karite terrain regions. Mining activities can also trigger sinkholes.",
        },
        {
            "slug": "extreme-sea-conditions", "name": "Extreme Sea Conditions", "icon": "🌊⚠️",
            "category": "Oceanic", "color_code": "#155e75", "display_order": 27,
            "short_description": "Dangerous ocean conditions including rough seas, high waves, and strong currents.",
            "india_relevance": "India's fishing communities are particularly vulnerable to rough sea conditions. INCOIS issues ocean state forecasts and high wave alerts for India's coastline.",
        },
        {
            "slug": "glof", "name": "Glacial Lake Outburst Flood (GLOF)", "icon": "🏔️🌊",
            "category": "Hydrological/Glaciological", "color_code": "#0e7490", "display_order": 28,
            "short_description": "Sudden release of water from a glacial lake, causing devastating downstream flooding.",
            "india_relevance": "GLOFs are a significant and growing threat in the Himalayas as glaciers retreat due to climate change. Uttarakhand, Himachal Pradesh, Sikkim, and Arunachal Pradesh are at risk. The 2021 Chamoli disaster in Uttarakhand was linked to glacial processes.",
        },
        {
            "slug": "biological-emergency", "name": "Biological Emergency", "icon": "🦠",
            "category": "Biological", "color_code": "#15803d", "display_order": 29,
            "short_description": "Outbreaks of infectious diseases, pandemics, or other biological hazards affecting public health.",
            "india_relevance": "India has faced numerous biological emergencies including the COVID-19 pandemic, Nipah virus outbreaks in Kerala, and annual outbreaks of dengue, malaria, and chikungunya.",
        },
        {
            "slug": "chemical-emergency", "name": "Chemical Emergency", "icon": "☣️",
            "category": "Technological", "color_code": "#a21caf", "display_order": 30,
            "short_description": "Accidental release of hazardous chemicals posing risks to health and environment.",
            "india_relevance": "India has experienced chemical disasters including the Bhopal gas tragedy (1984), one of the world's worst industrial disasters. Chemical industrial zones across India require strict safety monitoring.",
        },
        {
            "slug": "nuclear-radiological", "name": "Nuclear/Radiological Emergency", "icon": "☢️",
            "category": "Technological", "color_code": "#facc15", "display_order": 31,
            "short_description": "Release of radioactive materials from nuclear facilities or transportation accidents.",
            "india_relevance": "India operates multiple nuclear power plants. The Atomic Energy Regulatory Board (AERB) and NDMA have emergency response frameworks for nuclear/radiological incidents.",
        },
        {
            "slug": "industrial-disaster", "name": "Industrial Disaster", "icon": "🏭",
            "category": "Technological", "color_code": "#6b7280", "display_order": 32,
            "short_description": "Major accidents at industrial facilities causing explosions, fires, or hazardous releases.",
            "india_relevance": "India's industrial sector, including chemical plants, oil refineries, and manufacturing units, faces ongoing risks. The NDMA provides guidelines for industrial disaster management.",
        },
        {
            "slug": "major-fire", "name": "Major Fire", "icon": "🔥🏢",
            "category": "Technological", "color_code": "#c2410c", "display_order": 33,
            "short_description": "Large-scale fires in buildings, markets, or other structures causing significant damage.",
            "india_relevance": "Urban fires are a significant hazard in India, particularly in densely packed markets, high-rise buildings, and industrial areas. The National Fire Service and State Fire Services provide emergency response.",
        },
        {
            "slug": "urban-infrastructure-emergency", "name": "Urban/Infrastructure Emergency", "icon": "🏗️",
            "category": "Technological", "color_code": "#475569", "display_order": 34,
            "short_description": "Structural collapses, dam failures, bridge failures, and other infrastructure emergencies.",
            "india_relevance": "India faces infrastructure-related emergencies including building collapses (particularly unauthorized constructions), bridge failures, and dam safety concerns. The Dam Safety Act (2021) was enacted to improve dam monitoring.",
        }
    ]


def get_indian_states():
    """All 28 states and 8 union territories of India."""
    return [
        {"slug": "andhra-pradesh", "name": "Andhra Pradesh", "state_type": "state", "capital": "Amaravati", "latitude": 15.9129, "longitude": 79.7400, "region": "South", "is_coastal": True,
         "major_hazards": '["cyclone","flood","heatwave","drought","lightning","earthquake","storm-surge","coastal-flooding"]',
         "geography": "Located in southeastern India with a long coastline along the Bay of Bengal. The terrain includes coastal plains, the Eastern Ghats, and the Deccan Plateau.",
         "climate": "Tropical to semi-arid climate. Receives rainfall from both Southwest and Northeast monsoons. Prone to cyclones from the Bay of Bengal.",
         "seismic_zone": "Zone II-III"},
        {"slug": "arunachal-pradesh", "name": "Arunachal Pradesh", "state_type": "state", "capital": "Itanagar", "latitude": 28.2180, "longitude": 94.7278, "region": "Northeast", "is_himalayan": True,
         "major_hazards": '["earthquake","landslide","flood","flash-flood","cloudburst","glof"]',
         "geography": "Northeastern state bordering China, Myanmar, and Bhutan. Predominantly mountainous with dense forests.",
         "climate": "Sub-tropical to alpine climate. Heavy rainfall during monsoon season.",
         "seismic_zone": "Zone V"},
        {"slug": "assam", "name": "Assam", "state_type": "state", "capital": "Dispur", "latitude": 26.2006, "longitude": 92.9376, "region": "Northeast",
         "major_hazards": '["flood","earthquake","landslide","lightning","thunderstorm","extreme-rainfall","flash-flood"]',
         "geography": "Located in the Brahmaputra and Barak river valleys with surrounding hills. The Brahmaputra floodplain dominates central Assam.",
         "climate": "Tropical monsoon climate with heavy rainfall. One of the wettest regions in India.",
         "seismic_zone": "Zone V"},
        {"slug": "bihar", "name": "Bihar", "state_type": "state", "capital": "Patna", "latitude": 25.0961, "longitude": 85.3131, "region": "East",
         "major_hazards": '["flood","lightning","heatwave","earthquake","cold-wave","thunderstorm","drought"]',
         "geography": "Located in the eastern part of India, Bihar is a predominantly flat alluvial plain traversed by the Ganges and its tributaries.",
         "climate": "Subtropical climate with hot summers and cold winters. The monsoon brings heavy rainfall causing annual flooding.",
         "seismic_zone": "Zone IV-V",
         "disaster_history": "Bihar faces devastating floods almost every year, particularly in the Kosi, Gandak, and Bagmati river basins. The state also records among the highest lightning deaths in India. The 1934 Bihar-Nepal earthquake (M8.0) was one of the worst in Indian history."},
        {"slug": "chhattisgarh", "name": "Chhattisgarh", "state_type": "state", "capital": "Raipur", "latitude": 21.2787, "longitude": 81.8661, "region": "Central",
         "major_hazards": '["flood","lightning","heatwave","wildfire","thunderstorm","drought"]',
         "seismic_zone": "Zone II"},
        {"slug": "goa", "name": "Goa", "state_type": "state", "capital": "Panaji", "latitude": 15.2993, "longitude": 74.1240, "region": "West", "is_coastal": True,
         "major_hazards": '["flood","cyclone","coastal-flooding","extreme-rainfall","landslide"]',
         "seismic_zone": "Zone III"},
        {"slug": "gujarat", "name": "Gujarat", "state_type": "state", "capital": "Gandhinagar", "latitude": 22.2587, "longitude": 71.1924, "region": "West", "is_coastal": True,
         "major_hazards": '["earthquake","cyclone","flood","drought","heatwave","storm-surge","dust-storm"]',
         "seismic_zone": "Zone III-V",
         "disaster_history": "The 2001 Bhuj earthquake (M7.7) caused massive destruction in Gujarat, killing over 20,000 people. Cyclone Biparjoy (2023) also significantly affected the state."},
        {"slug": "haryana", "name": "Haryana", "state_type": "state", "capital": "Chandigarh", "latitude": 29.0588, "longitude": 76.0856, "region": "North",
         "major_hazards": '["flood","heatwave","cold-wave","lightning","thunderstorm","dust-storm"]',
         "seismic_zone": "Zone II-IV"},
        {"slug": "himachal-pradesh", "name": "Himachal Pradesh", "state_type": "state", "capital": "Shimla", "latitude": 31.1048, "longitude": 77.1734, "region": "North", "is_himalayan": True,
         "major_hazards": '["earthquake","landslide","flash-flood","avalanche","cloudburst","snowstorm","wildfire"]',
         "seismic_zone": "Zone IV-V"},
        {"slug": "jharkhand", "name": "Jharkhand", "state_type": "state", "capital": "Ranchi", "latitude": 23.6102, "longitude": 85.2799, "region": "East",
         "major_hazards": '["lightning","flood","heatwave","drought","thunderstorm","earthquake"]',
         "seismic_zone": "Zone II-III",
         "disaster_history": "Jharkhand records among the highest lightning-related deaths in India. The state is also affected by monsoon flooding and drought in different seasons."},
        {"slug": "karnataka", "name": "Karnataka", "state_type": "state", "capital": "Bengaluru", "latitude": 15.3173, "longitude": 75.7139, "region": "South", "is_coastal": True,
         "major_hazards": '["flood","drought","landslide","lightning","urban-flooding","cyclone","heatwave"]',
         "seismic_zone": "Zone II-III"},
        {"slug": "kerala", "name": "Kerala", "state_type": "state", "capital": "Thiruvananthapuram", "latitude": 10.8505, "longitude": 76.2711, "region": "South", "is_coastal": True,
         "major_hazards": '["flood","landslide","extreme-rainfall","cyclone","coastal-flooding","lightning","tsunami"]',
         "seismic_zone": "Zone III",
         "disaster_history": "The 2018 Kerala floods were the worst in the state in nearly a century, caused by extremely heavy rainfall and dam releases. The state also faced severe flooding in 2019 and 2021."},
        {"slug": "madhya-pradesh", "name": "Madhya Pradesh", "state_type": "state", "capital": "Bhopal", "latitude": 22.9734, "longitude": 78.6569, "region": "Central",
         "major_hazards": '["flood","heatwave","drought","lightning","thunderstorm","earthquake","wildfire"]',
         "seismic_zone": "Zone II-III",
         "disaster_history": "The 1984 Bhopal gas tragedy, one of the world's worst industrial disasters, occurred in Madhya Pradesh."},
        {"slug": "maharashtra", "name": "Maharashtra", "state_type": "state", "capital": "Mumbai", "latitude": 19.7515, "longitude": 75.7139, "region": "West", "is_coastal": True,
         "major_hazards": '["flood","urban-flooding","cyclone","drought","heatwave","landslide","earthquake","lightning"]',
         "seismic_zone": "Zone III",
         "disaster_history": "The 2005 Mumbai floods caused by 944mm rainfall in 24 hours, and the 1993 Latur earthquake (M6.2) are among Maharashtra's worst disasters."},
        {"slug": "manipur", "name": "Manipur", "state_type": "state", "capital": "Imphal", "latitude": 24.6637, "longitude": 93.9063, "region": "Northeast",
         "major_hazards": '["earthquake","landslide","flood","flash-flood"]',
         "seismic_zone": "Zone V"},
        {"slug": "meghalaya", "name": "Meghalaya", "state_type": "state", "capital": "Shillong", "latitude": 25.4670, "longitude": 91.3662, "region": "Northeast",
         "major_hazards": '["earthquake","landslide","flood","extreme-rainfall","lightning","flash-flood"]',
         "seismic_zone": "Zone V",
         "disaster_history": "Meghalaya is home to Cherrapunji and Mawsynram, among the wettest places on Earth. The 1897 Shillong earthquake (M8.1) was one of the most powerful in Indian history."},
        {"slug": "mizoram", "name": "Mizoram", "state_type": "state", "capital": "Aizawl", "latitude": 23.1645, "longitude": 92.9376, "region": "Northeast",
         "major_hazards": '["earthquake","landslide","flood","wildfire","flash-flood"]',
         "seismic_zone": "Zone V"},
        {"slug": "nagaland", "name": "Nagaland", "state_type": "state", "capital": "Kohima", "latitude": 26.1584, "longitude": 94.5624, "region": "Northeast",
         "major_hazards": '["earthquake","landslide","flood","flash-flood"]',
         "seismic_zone": "Zone V"},
        {"slug": "odisha", "name": "Odisha", "state_type": "state", "capital": "Bhubaneswar", "latitude": 20.9517, "longitude": 85.0985, "region": "East", "is_coastal": True,
         "major_hazards": '["cyclone","flood","storm-surge","heatwave","lightning","drought","coastal-flooding","tornado"]',
         "seismic_zone": "Zone II-III",
         "disaster_history": "The 1999 Odisha Super Cyclone killed over 10,000 people and remains one of India's worst natural disasters. Cyclone Fani (2019) was another extremely severe event. Odisha is one of the most cyclone-prone states in India."},
        {"slug": "punjab", "name": "Punjab", "state_type": "state", "capital": "Chandigarh", "latitude": 31.1471, "longitude": 75.3412, "region": "North",
         "major_hazards": '["flood","heatwave","cold-wave","dust-storm","lightning"]',
         "seismic_zone": "Zone III-IV"},
        {"slug": "rajasthan", "name": "Rajasthan", "state_type": "state", "capital": "Jaipur", "latitude": 27.0238, "longitude": 74.2179, "region": "West",
         "major_hazards": '["heatwave","drought","dust-storm","sandstorm","flood","cold-wave","earthquake","lightning"]',
         "seismic_zone": "Zone II-IV"},
        {"slug": "sikkim", "name": "Sikkim", "state_type": "state", "capital": "Gangtok", "latitude": 27.5330, "longitude": 88.5122, "region": "Northeast", "is_himalayan": True,
         "major_hazards": '["earthquake","landslide","flash-flood","glof","avalanche","cloudburst"]',
         "seismic_zone": "Zone IV-V",
         "disaster_history": "The 2011 Sikkim earthquake (M6.9) caused significant damage. The 2023 GLOF from South Lhonak Lake caused devastating flash floods in the Teesta River valley."},
        {"slug": "tamil-nadu", "name": "Tamil Nadu", "state_type": "state", "capital": "Chennai", "latitude": 11.1271, "longitude": 78.6569, "region": "South", "is_coastal": True,
         "major_hazards": '["cyclone","flood","urban-flooding","tsunami","coastal-flooding","drought","heatwave","lightning"]',
         "seismic_zone": "Zone II-III",
         "disaster_history": "The 2004 Indian Ocean tsunami devastated Tamil Nadu's coast. The 2015 Chennai floods caused by over 1000mm of rainfall in 3 days were catastrophic."},
        {"slug": "telangana", "name": "Telangana", "state_type": "state", "capital": "Hyderabad", "latitude": 18.1124, "longitude": 79.0193, "region": "South",
         "major_hazards": '["flood","urban-flooding","heatwave","drought","lightning","thunderstorm"]',
         "seismic_zone": "Zone II"},
        {"slug": "tripura", "name": "Tripura", "state_type": "state", "capital": "Agartala", "latitude": 23.9408, "longitude": 91.9882, "region": "Northeast",
         "major_hazards": '["earthquake","flood","landslide","lightning","thunderstorm"]',
         "seismic_zone": "Zone V"},
        {"slug": "uttar-pradesh", "name": "Uttar Pradesh", "state_type": "state", "capital": "Lucknow", "latitude": 26.8467, "longitude": 80.9462, "region": "North",
         "major_hazards": '["flood","lightning","heatwave","cold-wave","earthquake","drought","thunderstorm","dust-storm"]',
         "seismic_zone": "Zone II-IV"},
        {"slug": "uttarakhand", "name": "Uttarakhand", "state_type": "state", "capital": "Dehradun", "latitude": 30.0668, "longitude": 79.0193, "region": "North", "is_himalayan": True,
         "major_hazards": '["earthquake","landslide","flash-flood","cloudburst","avalanche","glof","wildfire","snowstorm"]',
         "seismic_zone": "Zone IV-V",
         "disaster_history": "The 2013 Uttarakhand disaster, triggered by cloudbursts and glacial lake overflow, killed thousands. The 2021 Chamoli disaster involved a rock-ice avalanche and flash floods."},
        {"slug": "west-bengal", "name": "West Bengal", "state_type": "state", "capital": "Kolkata", "latitude": 22.9868, "longitude": 87.8550, "region": "East", "is_coastal": True,
         "major_hazards": '["cyclone","flood","lightning","thunderstorm","storm-surge","heatwave","tornado","coastal-flooding"]',
         "seismic_zone": "Zone III-V",
         "disaster_history": "Cyclone Amphan (2020) was one of the strongest cyclones to hit West Bengal. The Sundarbans are particularly vulnerable to cyclones and storm surge. Bihar/Bengal region records among the highest lightning deaths in India."},
        # Union Territories
        {"slug": "andaman-nicobar", "name": "Andaman & Nicobar Islands", "state_type": "ut", "capital": "Port Blair", "latitude": 11.7401, "longitude": 92.6586, "region": "Islands", "is_coastal": True,
         "major_hazards": '["earthquake","tsunami","cyclone","volcanic-eruption","flood","coastal-flooding","storm-surge"]',
         "seismic_zone": "Zone V",
         "disaster_history": "Severely affected by the 2004 Indian Ocean tsunami. Located near the Sunda subduction zone and Barren Island (India's only active volcano)."},
        {"slug": "chandigarh", "name": "Chandigarh", "state_type": "ut", "capital": "Chandigarh", "latitude": 30.7333, "longitude": 76.7794, "region": "North",
         "major_hazards": '["earthquake","flood","heatwave","cold-wave","thunderstorm"]',
         "seismic_zone": "Zone IV"},
        {"slug": "dadra-nagar-haveli-daman-diu", "name": "Dadra & Nagar Haveli and Daman & Diu", "state_type": "ut", "capital": "Daman", "latitude": 20.1809, "longitude": 73.0169, "region": "West", "is_coastal": True,
         "major_hazards": '["cyclone","flood","coastal-flooding"]',
         "seismic_zone": "Zone III"},
        {"slug": "delhi", "name": "Delhi", "state_type": "ut", "capital": "New Delhi", "latitude": 28.7041, "longitude": 77.1025, "region": "North",
         "major_hazards": '["earthquake","flood","urban-flooding","heatwave","cold-wave","dust-storm","lightning","thunderstorm"]',
         "seismic_zone": "Zone IV",
         "disaster_history": "Delhi falls in Seismic Zone IV and faces risks from a potential large Himalayan earthquake. Urban flooding has increased in recent years. Extreme temperatures affect millions annually."},
        {"slug": "jammu-kashmir", "name": "Jammu & Kashmir", "state_type": "ut", "capital": "Srinagar / Jammu", "latitude": 33.7782, "longitude": 76.5762, "region": "North", "is_himalayan": True,
         "major_hazards": '["earthquake","landslide","avalanche","flood","flash-flood","snowstorm","cold-wave","cloudburst","glof"]',
         "seismic_zone": "Zone IV-V",
         "disaster_history": "The 2005 Kashmir earthquake (M7.6) caused massive destruction. The 2014 Jammu & Kashmir floods were the worst in 60 years, particularly devastating Srinagar."},
        {"slug": "ladakh", "name": "Ladakh", "state_type": "ut", "capital": "Leh", "latitude": 34.1526, "longitude": 77.5771, "region": "North", "is_himalayan": True,
         "major_hazards": '["earthquake","flash-flood","cloudburst","landslide","avalanche","cold-wave","glof"]',
         "seismic_zone": "Zone IV-V",
         "disaster_history": "The 2010 Leh cloudburst caused devastating flash floods, killing over 200 people."},
        {"slug": "lakshadweep", "name": "Lakshadweep", "state_type": "ut", "capital": "Kavaratti", "latitude": 10.5667, "longitude": 72.6417, "region": "Islands", "is_coastal": True,
         "major_hazards": '["cyclone","tsunami","coastal-flooding","storm-surge","extreme-sea-conditions"]',
         "seismic_zone": "Zone III"},
        {"slug": "puducherry", "name": "Puducherry", "state_type": "ut", "capital": "Puducherry", "latitude": 11.9416, "longitude": 79.8083, "region": "South", "is_coastal": True,
         "major_hazards": '["cyclone","flood","tsunami","coastal-flooding","heatwave"]',
         "seismic_zone": "Zone II-III"},
    ]


def get_data_sources():
    """Official data source registry."""
    return [
        {
            "source_id": "usgs", "name": "United States Geological Survey (USGS)",
            "country": "United States", "agency": "U.S. Department of the Interior",
            "api_url": "https://earthquake.usgs.gov/fdsnws/event/1/query",
            "website": "https://earthquake.usgs.gov",
            "data_types": '["earthquake"]',
            "update_frequency": "Real-time (within minutes)",
            "license_info": "Public domain, freely available",
            "limitations": "Global coverage but may not capture all small/local events in India. Primarily seismic data.",
            "status": "operational", "priority": 1
        },
        {
            "source_id": "imd", "name": "India Meteorological Department (IMD)",
            "country": "India", "agency": "Ministry of Earth Sciences",
            "website": "https://mausam.imd.gov.in",
            "data_types": '["cyclone","heatwave","cold-wave","thunderstorm","extreme-rainfall","drought"]',
            "update_frequency": "Multiple times daily",
            "limitations": "Official forecasts and warnings for India. API access may be limited.",
            "status": "operational", "priority": 1
        },
        {
            "source_id": "incois", "name": "Indian National Centre for Ocean Information Services (INCOIS)",
            "country": "India", "agency": "Ministry of Earth Sciences",
            "website": "https://incois.gov.in",
            "data_types": '["tsunami","extreme-sea-conditions","storm-surge"]',
            "update_frequency": "Real-time for tsunami warnings",
            "limitations": "India's official tsunami and ocean information authority.",
            "status": "operational", "priority": 1
        },
        {
            "source_id": "ndma", "name": "National Disaster Management Authority (NDMA)",
            "country": "India", "agency": "Ministry of Home Affairs",
            "website": "https://ndma.gov.in",
            "data_types": '["earthquake","cyclone","flood","tsunami","landslide","heatwave","cold-wave","lightning","wildfire"]',
            "update_frequency": "As needed during events",
            "limitations": "Policy and coordination body. Provides guidelines and alerts through SACHET platform.",
            "status": "operational", "priority": 1
        },
        {
            "source_id": "cwc", "name": "Central Water Commission (CWC)",
            "country": "India", "agency": "Ministry of Jal Shakti",
            "website": "https://cwc.gov.in",
            "data_types": '["flood"]',
            "update_frequency": "Daily during monsoon, real-time during floods",
            "limitations": "Monitors river water levels and flood forecasting for major rivers in India.",
            "status": "operational", "priority": 1
        },
        {
            "source_id": "gsi", "name": "Geological Survey of India (GSI)",
            "country": "India", "agency": "Ministry of Mines",
            "website": "https://www.gsi.gov.in",
            "data_types": '["landslide","earthquake"]',
            "update_frequency": "Periodic reports and during events",
            "limitations": "Provides geological surveys and landslide monitoring.",
            "status": "operational", "priority": 2
        },
        {
            "source_id": "fsi", "name": "Forest Survey of India (FSI)",
            "country": "India", "agency": "Ministry of Environment, Forest and Climate Change",
            "website": "https://fsi.nic.in",
            "data_types": '["wildfire"]',
            "update_frequency": "Near real-time fire alerts via satellite",
            "limitations": "Monitors forest fire incidents across India using satellite data.",
            "status": "operational", "priority": 2
        },
    ]


def get_emergency_contacts():
    """Verified emergency contact numbers for India."""
    return [
        {"service": "National Emergency Number", "number": "112", "country": "India", "source": "Government of India"},
        {"service": "Police", "number": "100", "country": "India", "source": "Government of India"},
        {"service": "Fire", "number": "101", "country": "India", "source": "Government of India"},
        {"service": "Ambulance", "number": "102", "country": "India", "source": "Government of India"},
        {"service": "Ambulance (EMRI)", "number": "108", "country": "India", "source": "EMRI"},
        {"service": "Disaster Management (NDMA)", "number": "1078", "country": "India", "source": "NDMA"},
        {"service": "Women Helpline", "number": "1091", "country": "India", "source": "Government of India"},
        {"service": "Child Helpline", "number": "1098", "country": "India", "source": "Government of India"},
        {"service": "Indian Coast Guard", "number": "1554", "country": "India", "source": "Indian Coast Guard"},
        {"service": "Earthquake / Tsunami Helpline (INCOIS)", "number": "1800-425-2566", "country": "India", "source": "INCOIS", "notes": "Toll-free tsunami and earthquake information"},
        {"service": "Road Accident Emergency", "number": "1073", "country": "India", "source": "Government of India"},
    ]


def get_glossary_terms():
    """Key disaster terminology."""
    return [
        {"slug": "epicenter", "term": "Epicenter", "category": "Earthquake",
         "simple_definition": "The point on the Earth's surface directly above where an earthquake originates.",
         "scientific_definition": "The point on the Earth's surface vertically above the hypocenter (focus) of an earthquake, where the seismic rupture initiates.",
         "example": "The epicenter of the 2001 Bhuj earthquake was located near the town of Bhuj in Gujarat, India.",
         "related_hazards": '["earthquake"]'},
        {"slug": "hypocenter", "term": "Hypocenter (Focus)", "category": "Earthquake",
         "simple_definition": "The underground point where an earthquake actually begins.",
         "scientific_definition": "The point within the Earth where an earthquake rupture starts, located at a specific depth below the epicenter.",
         "example": "A shallow earthquake has its hypocenter less than 70 km deep, making surface shaking more intense.",
         "related_hazards": '["earthquake"]'},
        {"slug": "magnitude", "term": "Magnitude", "category": "Earthquake",
         "simple_definition": "A number that measures the size and energy released by an earthquake.",
         "scientific_definition": "A logarithmic measure of the size of an earthquake at its source. The moment magnitude scale (Mw) is the most widely used, replacing the older Richter scale for larger earthquakes. Each whole number increase represents approximately 31.6 times more energy.",
         "example": "A magnitude 7.0 earthquake releases about 1,000 times more energy than a magnitude 5.0 earthquake.",
         "related_hazards": '["earthquake"]'},
        {"slug": "aftershock", "term": "Aftershock", "category": "Earthquake",
         "simple_definition": "A smaller earthquake that occurs after a larger earthquake in the same area.",
         "scientific_definition": "Earthquakes that follow the largest shock of an earthquake sequence, occurring in or near the rupture zone of the initial event as the surrounding crust adjusts to the new stress conditions.",
         "example": "After the 2015 Nepal earthquake (M7.8), hundreds of aftershocks were recorded in the following weeks, including a M7.3 event.",
         "related_hazards": '["earthquake"]'},
        {"slug": "fault", "term": "Fault", "category": "Earthquake",
         "simple_definition": "A crack in the Earth's crust where blocks of rock have moved past each other.",
         "scientific_definition": "A planar fracture or discontinuity in a volume of rock across which there has been significant displacement. Major types include normal faults, reverse (thrust) faults, and strike-slip faults.",
         "related_hazards": '["earthquake","landslide"]'},
        {"slug": "seismic-wave", "term": "Seismic Wave", "category": "Earthquake",
         "simple_definition": "Waves of energy that travel through the Earth during an earthquake, causing the ground to shake.",
         "scientific_definition": "Waves of energy that propagate through the Earth's interior (body waves: P-waves and S-waves) and along the surface (surface waves: Love waves and Rayleigh waves) as a result of an earthquake or explosion.",
         "related_hazards": '["earthquake"]'},
        {"slug": "tsunami-wave", "term": "Tsunami Wave", "category": "Tsunami",
         "simple_definition": "A very long ocean wave caused by underwater earthquakes or volcanic eruptions that can cause massive coastal flooding.",
         "scientific_definition": "A series of ocean waves with extremely long wavelengths (up to hundreds of kilometres) generated by impulsive displacement of a large volume of water. In deep water, tsunami waves travel at speeds proportional to the square root of ocean depth.",
         "related_hazards": '["tsunami","earthquake","volcanic-eruption"]'},
        {"slug": "storm-surge-term", "term": "Storm Surge", "category": "Cyclone",
         "simple_definition": "An abnormal rise of sea level caused by a cyclone's winds pushing ocean water onto shore.",
         "scientific_definition": "The rise in seawater level due to the combined effect of low atmospheric pressure and wind-driven wave action during a tropical cyclone, measured as the difference between the observed and normal (astronomically predicted) tide level.",
         "example": "The 1999 Odisha Super Cyclone produced a storm surge of up to 8 metres, devastating the coastal districts.",
         "related_hazards": '["cyclone","storm-surge","coastal-flooding"]'},
        {"slug": "eye", "term": "Eye (of a Cyclone)", "category": "Cyclone",
         "simple_definition": "The calm center of a cyclone, surrounded by the most intense winds.",
         "scientific_definition": "A roughly circular area of relatively light winds and clear skies at the centre of a tropical cyclone, surrounded by the eyewall where the strongest winds occur.",
         "related_hazards": '["cyclone"]'},
        {"slug": "eyewall", "term": "Eyewall", "category": "Cyclone",
         "simple_definition": "The ring of intense thunderstorms surrounding the eye of a cyclone, where the strongest winds are found.",
         "scientific_definition": "The organized ring of cumulonimbus clouds surrounding the eye of a tropical cyclone, containing the most severe weather including the strongest winds and heaviest precipitation.",
         "related_hazards": '["cyclone"]'},
        {"slug": "flash-flood-term", "term": "Flash Flood", "category": "Flood",
         "simple_definition": "A sudden, rapid flood caused by intense rainfall in a short time, often in hilly or urban areas.",
         "scientific_definition": "A rapid-onset flood of short duration with a relatively high peak discharge, typically occurring within six hours of heavy rainfall or other cause.",
         "related_hazards": '["flash-flood","flood","cloudburst","extreme-rainfall"]'},
        {"slug": "cloudburst-term", "term": "Cloudburst", "category": "Meteorological",
         "simple_definition": "An extreme, sudden rainfall event where a large amount of rain falls in a very short time over a small area.",
         "scientific_definition": "An intense but short-lived rainfall event, typically defined as rainfall exceeding 100 mm (10 cm) in one hour over a small geographic area (usually less than 20-30 sq km).",
         "example": "The 2013 Kedarnath cloudburst in Uttarakhand triggered devastating flash floods and landslides.",
         "related_hazards": '["cloudburst","flash-flood","landslide","extreme-rainfall"]'},
        {"slug": "pyroclastic-flow", "term": "Pyroclastic Flow", "category": "Volcanic",
         "simple_definition": "A fast-moving cloud of extremely hot gas and volcanic fragments that rushes down a volcano's slope.",
         "scientific_definition": "A dense, destructive mass of very hot ash, lava fragments, and gases ejected explosively from a volcano, which flows rapidly down its flanks at speeds that can exceed 700 km/h and temperatures above 700°C.",
         "related_hazards": '["volcanic-eruption"]'},
        {"slug": "lahar", "term": "Lahar", "category": "Volcanic",
         "simple_definition": "A destructive mudflow composed of volcanic debris and water that flows rapidly down a volcano.",
         "scientific_definition": "A type of mudflow or debris flow composed of pyroclastic material, rocky debris, and water that flows from a volcano, typically along river valleys.",
         "related_hazards": '["volcanic-eruption","landslide"]'},
        {"slug": "liquefaction", "term": "Liquefaction", "category": "Earthquake",
         "simple_definition": "When loose, water-saturated soil temporarily behaves like a liquid during earthquake shaking.",
         "scientific_definition": "A phenomenon in which saturated, unconsolidated soil or sand temporarily loses its strength and behaves as a fluid during strong ground shaking, causing buildings to sink and tilt.",
         "related_hazards": '["earthquake"]'},
        {"slug": "glof-term", "term": "GLOF (Glacial Lake Outburst Flood)", "category": "Glaciological",
         "simple_definition": "A sudden, catastrophic flood caused by the failure of a natural dam holding back a glacial lake.",
         "scientific_definition": "A type of outburst flood that occurs when the dam containing a glacial lake fails, releasing large volumes of water and debris downstream. Causes include moraine dam failure, ice avalanches, and glacial retreat.",
         "example": "The 2023 South Lhonak Lake GLOF in Sikkim caused devastating floods in the Teesta River valley.",
         "related_hazards": '["glof","flash-flood","flood"]'},
        {"slug": "heat-index", "term": "Heat Index", "category": "Meteorological",
         "simple_definition": "A measure of how hot it really feels when humidity is combined with the actual air temperature.",
         "scientific_definition": "An index that combines air temperature and relative humidity to determine an apparent temperature — how hot it feels to the human body. High heat index values indicate increased risk of heat-related illness.",
         "related_hazards": '["heatwave"]'},
        {"slug": "tectonic-plate", "term": "Tectonic Plate", "category": "Geological",
         "simple_definition": "Large sections of the Earth's outer shell that slowly move, float, and sometimes collide with each other.",
         "scientific_definition": "A massive, irregularly shaped slab of solid rock, generally composed of both continental and oceanic lithosphere, that moves relative to other plates on the asthenosphere.",
         "related_hazards": '["earthquake","volcanic-eruption","tsunami"]'},
        {"slug": "richter-scale", "term": "Richter Scale", "category": "Earthquake",
         "simple_definition": "An older scale used to measure the size of earthquakes, now largely replaced by the moment magnitude scale.",
         "scientific_definition": "A logarithmic scale developed by Charles Richter in 1935 to measure the magnitude of local earthquakes. It has been superseded by the moment magnitude scale (Mw) for medium and large earthquakes.",
         "related_hazards": '["earthquake"]'},
        {"slug": "seismic-zone", "term": "Seismic Zone", "category": "Earthquake",
         "simple_definition": "A region classified by its level of earthquake risk based on past seismic activity and geology.",
         "scientific_definition": "A geographic area defined on the basis of observed seismicity, geology, and tectonics, representing a certain level of seismic hazard. India uses a four-zone classification (II through V) established by the Bureau of Indian Standards.",
         "related_hazards": '["earthquake"]'},
    ]


def get_safety_guides():
    """Safety guides for major disaster types."""
    return [
        {
            "disaster_slug": "earthquake",
            "title": "Earthquake Safety Guide",
            "before_steps": json.dumps([
                "Secure heavy furniture, water heaters, and large appliances to walls using straps or bolts",
                "Prepare an emergency kit with water, food, flashlight, batteries, first aid supplies, and important documents",
                "Identify safe spots in every room — under sturdy tables or desks, against interior walls",
                "Learn and practice 'Drop, Cover, and Hold On' with your family",
                "Know how to turn off gas, water, and electricity in your home",
                "Plan evacuation routes and identify safe meeting points",
                "Keep shoes and a flashlight near your bed",
                "Store emergency water supply — at least 4 litres per person per day for 3 days"
            ]),
            "during_steps": json.dumps([
                "DROP to your hands and knees immediately",
                "Take COVER under a sturdy desk, table, or against an interior wall",
                "HOLD ON until the shaking stops",
                "Stay away from windows, mirrors, and heavy objects that could fall",
                "If in bed, stay there and protect your head with a pillow",
                "Do NOT run outside during shaking — falling debris is the main danger",
                "Do NOT use elevators",
                "If outdoors, move to an open area away from buildings, power lines, and trees",
                "If driving, pull over safely, stop, and stay inside the vehicle"
            ]),
            "after_steps": json.dumps([
                "Check yourself and others for injuries — provide first aid if needed",
                "Be prepared for aftershocks — they may be strong",
                "Move carefully and watch for fallen debris, broken glass, and damaged structures",
                "Do NOT enter damaged buildings",
                "Check for gas leaks, electrical damage, and water line breaks",
                "Listen to official emergency broadcasts for instructions",
                "Use text messages instead of phone calls to keep lines open for emergencies",
                "If near the coast, move to higher ground — a tsunami may follow",
                "Document damage with photographs for insurance purposes"
            ]),
            "source": "Adapted from NDMA, USGS, and international earthquake safety guidelines"
        },
        {
            "disaster_slug": "cyclone",
            "title": "Cyclone Safety Guide",
            "before_steps": json.dumps([
                "Monitor IMD weather forecasts and cyclone bulletins regularly",
                "Secure loose objects outside your home — trim branches, secure outdoor furniture",
                "Stock up on emergency supplies: water, food, medicines, flashlight, batteries, power bank",
                "Charge all mobile phones and portable devices fully",
                "Keep important documents in waterproof bags",
                "Identify the nearest cyclone shelter or sturdy building",
                "If in an evacuation zone, prepare to evacuate when ordered by authorities",
                "Board up windows or protect them with storm shutters",
                "Fill bathtubs and containers with clean water for emergencies",
                "Secure your vehicle in a safe location"
            ]),
            "during_steps": json.dumps([
                "Stay indoors in a strong, well-built structure",
                "Stay away from windows, glass doors, and exterior walls",
                "Move to an interior room on the lowest floor",
                "Do NOT go outside during the storm — even if it seems calm (it may be the eye)",
                "Do NOT walk or drive through floodwaters",
                "If trapped in flooding, move to the highest point and signal for help",
                "Listen to official weather updates on battery-powered radio or mobile phone",
                "Avoid using electrical equipment during the storm",
                "Beware of storm surge if near the coast"
            ]),
            "after_steps": json.dumps([
                "Remain indoors until authorities declare it safe",
                "Avoid downed power lines and flooded areas",
                "Do NOT drink tap water until authorities confirm it is safe",
                "Be cautious of damaged structures — they may collapse",
                "Watch for snakes, insects, and other animals displaced by flooding",
                "Report damaged infrastructure to local authorities",
                "Follow official instructions for relief and assistance",
                "Help injured neighbours if you can do so safely"
            ]),
            "source": "Adapted from NDMA and IMD cyclone safety guidelines"
        },
        {
            "disaster_slug": "flood",
            "title": "Flood Safety Guide",
            "before_steps": json.dumps([
                "Know your area's flood risk — check if you live in a flood-prone zone",
                "Monitor weather forecasts and flood warnings from CWC and IMD",
                "Prepare an emergency kit and keep it in an easily accessible, elevated location",
                "Store important documents in waterproof containers on upper floors",
                "Know your evacuation routes and nearest shelters",
                "Do NOT build or store valuables in basement areas in flood-prone regions",
                "Keep sandbags ready if flooding is common in your area",
                "Install check valves in plumbing to prevent floodwater backup"
            ]),
            "during_steps": json.dumps([
                "NEVER walk, swim, or drive through floodwater — it takes only 15 cm of fast-moving water to knock you down",
                "Move to higher ground immediately if flooding begins",
                "Follow evacuation orders without delay",
                "Stay away from rivers, streams, and drainage channels during heavy rain",
                "Avoid contact with floodwater — it may be contaminated with sewage, chemicals, or debris",
                "If trapped, go to the highest floor or roof and signal for rescue",
                "Do NOT touch electrical equipment if you are wet or standing in water",
                "Avoid bridges over fast-moving water"
            ]),
            "after_steps": json.dumps([
                "Return home only when authorities say it is safe",
                "Avoid walking through moving floodwater during cleanup",
                "Clean and disinfect everything that got wet — floodwater carries bacteria and contaminants",
                "Throw away food that has come into contact with floodwater",
                "Check for structural damage before entering your home",
                "Have an electrician check wiring before turning on electricity",
                "Watch for snakes and other displaced animals",
                "Document all damage for insurance claims and government assistance"
            ]),
            "source": "Adapted from NDMA, CWC, and international flood safety guidelines"
        },
        {
            "disaster_slug": "lightning",
            "title": "Lightning Safety Guide",
            "before_steps": json.dumps([
                "Monitor weather forecasts for thunderstorm warnings",
                "Plan outdoor activities to avoid peak thunderstorm hours",
                "Identify safe buildings or vehicles you can reach quickly when outdoors",
                "Install lightning protection systems on buildings where feasible",
                "Unplug sensitive electronics during thunderstorms to prevent surge damage"
            ]),
            "during_steps": json.dumps([
                "Move indoors immediately when you hear thunder or see lightning — follow the 30-30 rule",
                "AVOID open fields, hilltops, and high ground",
                "AVOID isolated tall trees — do NOT shelter under a single tree",
                "AVOID water — get out of swimming pools, lakes, and rivers immediately",
                "AVOID metal objects — fences, poles, umbrellas, bicycles",
                "If indoors, stay away from windows and avoid using wired phones",
                "Do NOT lie flat on the ground if caught outside — crouch low with feet together",
                "If in a group, spread out to reduce the risk of multiple casualties",
                "A vehicle with a hard top (not a convertible) provides reasonable protection"
            ]),
            "after_steps": json.dumps([
                "Wait at least 30 minutes after the last thunder before going outside",
                "Call emergency services if anyone is struck by lightning — lightning victims do NOT carry an electrical charge and can be safely touched",
                "Begin CPR immediately if the person is not breathing",
                "Check for burns, especially at lightning entry and exit points",
                "Be aware that storms may return — continue monitoring weather"
            ]),
            "source": "Adapted from NDMA, IMD, and international lightning safety guidelines"
        },
        {
            "disaster_slug": "tsunami",
            "title": "Tsunami Safety Guide",
            "before_steps": json.dumps([
                "Know if you live or work in a tsunami hazard zone (coastal areas, especially low-lying regions)",
                "Learn the natural warning signs: strong earthquake felt near the coast, unusual ocean behaviour (rapid sea level drop), loud roaring sound from the ocean",
                "Know your evacuation routes to higher ground — practice them",
                "Have an emergency kit ready with essential supplies",
                "Register for tsunami alerts from INCOIS if available",
                "If you live in a coastal area, identify the nearest high ground or upper floors of reinforced concrete buildings"
            ]),
            "during_steps": json.dumps([
                "If you feel a strong earthquake near the coast, move IMMEDIATELY to higher ground — do NOT wait for an official warning",
                "If the ocean recedes unusually far, it is a natural warning — move inland or to high ground immediately",
                "Move to an elevation of at least 30 metres or at least 2 km inland",
                "If you cannot reach high ground, go to the upper floors (3rd floor or higher) of a strong reinforced concrete building",
                "NEVER go to the coast to watch a tsunami",
                "Stay away from rivers and streams that lead to the ocean",
                "Follow official INCOIS and NDMA alerts and instructions"
            ]),
            "after_steps": json.dumps([
                "Stay away from flooded and damaged areas until authorities declare them safe",
                "Multiple waves may arrive over several hours — do NOT return to low-lying areas after the first wave",
                "Wait for official all-clear from INCOIS before returning",
                "Avoid floodwater — it may be contaminated",
                "Be aware of secondary hazards: damaged structures, displaced objects, contaminated water",
                "Help injured people if you can do so safely",
                "Follow official instructions for relief and assistance"
            ]),
            "source": "Adapted from INCOIS, NDMA, and IOC/UNESCO tsunami safety guidelines"
        },
        {
            "disaster_slug": "heatwave",
            "title": "Heatwave Safety Guide",
            "before_steps": json.dumps([
                "Monitor IMD heatwave warnings and forecasts",
                "Stock up on water and oral rehydration solutions",
                "Plan outdoor activities for cooler parts of the day (early morning or late evening)",
                "Check on elderly neighbours, young children, and people with chronic illnesses",
                "Ensure your home has adequate ventilation or cooling",
                "Prepare light, loose-fitting, light-coloured clothing"
            ]),
            "during_steps": json.dumps([
                "Stay hydrated — drink water regularly, even if not thirsty",
                "Avoid going outdoors during peak heat (12 PM to 4 PM)",
                "Wear light, loose-fitting, light-coloured clothing and a hat or umbrella",
                "Never leave children or pets in parked vehicles",
                "Avoid strenuous physical activity during peak heat",
                "Use ORS (Oral Rehydration Solution) or homemade alternatives (water with salt and sugar)",
                "Recognise heat-related illness symptoms: heavy sweating, weakness, nausea, dizziness, fast pulse",
                "If someone shows signs of heatstroke (high body temperature, confusion, loss of consciousness), call emergency services immediately and cool the person down"
            ]),
            "after_steps": json.dumps([
                "Continue drinking water and staying cool even after temperatures drop",
                "Monitor for delayed symptoms of heat-related illness",
                "Check on vulnerable community members",
                "Follow official health advisories"
            ]),
            "source": "Adapted from NDMA and IMD heatwave guidelines"
        },
        {
            "disaster_slug": "landslide",
            "title": "Landslide Safety Guide",
            "before_steps": json.dumps([
                "Be aware if you live in a landslide-prone area (steep slopes, previous landslide zones, areas with heavy rainfall)",
                "Monitor weather warnings during heavy rainfall — landslides often follow prolonged or intense rain",
                "Watch for warning signs: cracks in ground or walls, tilting trees or poles, unusual water seepage, rumbling sounds from hillside",
                "Know your evacuation routes away from slopes",
                "Avoid building on steep slopes, near mountain edges, or in natural drainage channels"
            ]),
            "during_steps": json.dumps([
                "If you hear rumbling, notice ground movement, or see debris flow, move away from the path IMMEDIATELY",
                "Move perpendicular to the direction of landslide movement — do NOT try to outrun it downhill",
                "If inside a building and escape is not possible, curl into a tight ball and protect your head",
                "Stay alert during and after heavy rainfall in hilly areas",
                "Avoid river valleys and low areas during heavy rain in mountainous regions"
            ]),
            "after_steps": json.dumps([
                "Stay away from the landslide area — additional slides may occur",
                "Report the landslide to local authorities",
                "Help injured people without entering the unstable area",
                "Check for damaged utility lines and infrastructure",
                "Do NOT enter damaged buildings until inspected by authorities",
                "Watch for flooding that may follow landslides due to blocked waterways"
            ]),
            "source": "Adapted from NDMA, GSI, and international landslide safety guidelines"
        },
        {
            "disaster_slug": "wildfire",
            "title": "Wildfire / Forest Fire Safety Guide",
            "before_steps": json.dumps([
                "If you live near forests or dry grasslands, maintain a defensible space around your home",
                "Clear dry vegetation, leaves, and debris from around your property",
                "Keep emergency supplies ready including N95 masks for smoke",
                "Know your evacuation routes",
                "Monitor fire weather warnings from local authorities and FSI"
            ]),
            "during_steps": json.dumps([
                "Evacuate immediately if ordered by authorities — do NOT wait",
                "If caught in smoke, stay low where air is cleaner",
                "Cover your nose and mouth with a wet cloth",
                "Close all windows and doors if sheltering in a building",
                "Do NOT attempt to fight a large wildfire yourself",
                "Drive slowly with headlights on if evacuating through smoke"
            ]),
            "after_steps": json.dumps([
                "Return only when authorities declare it safe",
                "Watch for hotspots and smouldering debris",
                "Avoid damaged or fallen power lines",
                "Use masks to protect against ash and smoke particles",
                "Document damage for insurance and relief purposes"
            ]),
            "source": "Adapted from NDMA and FSI fire safety guidelines"
        },
    ]


def get_historical_events():
    """Major historical disasters (verified, sourced)."""
    return [
        {"disaster_type": "earthquake", "title": "1934 Bihar-Nepal Earthquake", "year": 1934, "country": "India", "state": "Bihar",
         "location": "Bihar-Nepal border region", "magnitude": 8.0, "deaths": 10700,
         "description": "One of the worst earthquakes in Indian history, causing massive destruction across Bihar and Nepal. The earthquake triggered widespread liquefaction in the Gangetic plains.",
         "source": "USGS, GSI historical records"},
        {"disaster_type": "earthquake", "title": "1950 Assam-Tibet Earthquake", "year": 1950, "country": "India", "state": "Assam",
         "location": "Assam-Tibet border", "magnitude": 8.6, "deaths": 1526,
         "description": "One of the largest earthquakes ever recorded. It caused massive landslides, altered river courses, and triggered flooding that affected communities for months afterward.",
         "source": "USGS, GSI historical records"},
        {"disaster_type": "earthquake", "title": "1993 Latur Earthquake", "year": 1993, "country": "India", "state": "Maharashtra",
         "location": "Latur-Osmanabad, Maharashtra", "magnitude": 6.2, "deaths": 9748,
         "description": "A devastating earthquake in peninsular India, an area considered relatively stable. The high death toll was largely due to the collapse of traditional stone and mud buildings during the early morning hours.",
         "source": "USGS, GSI historical records"},
        {"disaster_type": "earthquake", "title": "2001 Bhuj Earthquake", "year": 2001, "country": "India", "state": "Gujarat",
         "location": "Bhuj, Gujarat", "magnitude": 7.7, "deaths": 20000,
         "description": "One of India's deadliest earthquakes, devastating the Kutch region of Gujarat on Republic Day. It led to significant improvements in India's building codes and disaster management frameworks.",
         "source": "USGS, NDMA"},
        {"disaster_type": "earthquake", "title": "2015 Nepal Earthquake", "year": 2015, "country": "Nepal",
         "location": "Gorkha, Nepal", "magnitude": 7.8, "deaths": 8964,
         "description": "A catastrophic earthquake that devastated Nepal and was strongly felt across northern India, particularly Bihar and Uttar Pradesh. It destroyed historic temples and structures in the Kathmandu Valley.",
         "source": "USGS"},
        {"disaster_type": "tsunami", "title": "2004 Indian Ocean Tsunami", "year": 2004, "country": "Multi-country",
         "location": "Indian Ocean (Indonesia, Sri Lanka, India, Thailand and others)", "magnitude": 9.1, "deaths": 227898,
         "description": "Triggered by a massive undersea earthquake off Sumatra, this tsunami devastated coastlines across the Indian Ocean. In India, Tamil Nadu, Andaman & Nicobar Islands, Kerala, and Andhra Pradesh were severely affected, with over 10,000 deaths. It led to the establishment of the Indian Tsunami Early Warning Centre at INCOIS.",
         "source": "USGS, INCOIS, NOAA"},
        {"disaster_type": "cyclone", "title": "1999 Odisha Super Cyclone", "year": 1999, "country": "India", "state": "Odisha",
         "location": "Odisha coast", "severity": "Super Cyclone", "deaths": 10000,
         "description": "One of the deadliest tropical cyclones in Indian history, with wind speeds exceeding 260 km/h and a storm surge of up to 8 metres. It devastated 14 districts of Odisha. This disaster catalyzed major improvements in India's cyclone preparedness and early warning systems.",
         "source": "IMD, NDMA"},
        {"disaster_type": "cyclone", "title": "Cyclone Fani (2019)", "year": 2019, "country": "India", "state": "Odisha",
         "location": "Odisha coast (landfall near Puri)", "severity": "Extremely Severe", "deaths": 89,
         "description": "An extremely severe cyclone that made landfall near Puri with winds up to 215 km/h. Despite its intensity, the death toll was remarkably low due to the massive evacuation of 1.2 million people — demonstrating the improvement in India's disaster preparedness since 1999.",
         "source": "IMD, NDMA"},
        {"disaster_type": "cyclone", "title": "Cyclone Amphan (2020)", "year": 2020, "country": "India", "state": "West Bengal",
         "location": "West Bengal coast (landfall near Sundarbans)", "severity": "Super Cyclone", "deaths": 128,
         "description": "The strongest cyclone to form in the Bay of Bengal since 1999, causing massive damage to Kolkata and the Sundarbans.",
         "source": "IMD"},
        {"disaster_type": "flood", "title": "2013 Uttarakhand Disaster", "year": 2013, "country": "India", "state": "Uttarakhand",
         "location": "Kedarnath and surrounding areas, Uttarakhand", "deaths": 5748,
         "description": "Triggered by heavy rainfall, cloudbursts, and glacial lake overflow, massive flash floods and landslides devastated the Kedarnath Valley and surrounding areas. Often called the 'Himalayan Tsunami', it trapped thousands of pilgrims and tourists.",
         "source": "NDMA, GSI"},
        {"disaster_type": "flood", "title": "2018 Kerala Floods", "year": 2018, "country": "India", "state": "Kerala",
         "location": "Kerala (statewide)", "deaths": 483,
         "description": "The worst flooding in Kerala in nearly a century, caused by unusually heavy monsoon rainfall. All 14 districts were placed on red alert, 35 of 54 dams were opened, and over 1 million people were displaced.",
         "source": "NDMA, IMD, Kerala State Disaster Management Authority"},
        {"disaster_type": "flood", "title": "2005 Mumbai Floods", "year": 2005, "country": "India", "state": "Maharashtra",
         "location": "Mumbai, Maharashtra", "deaths": 1094,
         "description": "Caused by an extraordinary 944mm of rainfall in 24 hours on 26 July 2005, the floods paralyzed Mumbai. It exposed the vulnerability of India's financial capital to extreme rainfall and inadequate urban drainage.",
         "source": "IMD, Municipal Corporation of Greater Mumbai"},
        {"disaster_type": "chemical-emergency", "title": "1984 Bhopal Gas Tragedy", "year": 1984, "country": "India", "state": "Madhya Pradesh",
         "location": "Bhopal, Madhya Pradesh", "deaths": 3787,
         "description": "One of the world's worst industrial disasters. A leak of methyl isocyanate gas from the Union Carbide India Limited pesticide plant exposed over 500,000 people to toxic gases. The official immediate death toll was 3,787, though estimates of total deaths including long-term effects are much higher.",
         "source": "Government of India, Madhya Pradesh State Government"},
    ]


def seed_all(db, models):
    """Seeds database tables if empty."""
    try:
        if models.DisasterType.query.first() is not None:
            print("Database already seeded with disaster data.")
            return

        print("Seeding database with multi-disaster platform data...")

        # 1. Disaster Types
        for d in get_disaster_types():
            obj = models.DisasterType(**d)
            db.session.add(obj)

        # 2. Indian States
        for s in get_indian_states():
            obj = models.IndianState(**s)
            db.session.add(obj)

        # 3. Glossary Terms
        for g in get_glossary_terms():
            obj = models.GlossaryTerm(**g)
            db.session.add(obj)

        # 4. Emergency Contacts
        for c in get_emergency_contacts():
            obj = models.EmergencyContact(**c)
            db.session.add(obj)

        # 5. Data Sources
        for ds in get_data_sources():
            obj = models.DataSource(**ds)
            db.session.add(obj)

        # 6. Safety Guides
        for sg in get_safety_guides():
            obj = models.SafetyGuide(**sg)
            db.session.add(obj)

        # 7. Historical Events
        for he in get_historical_events():
            obj = models.HistoricalEvent(**he)
            db.session.add(obj)

        db.session.commit()
        print("Database seeding completed successfully!")
    except Exception as e:
        db.session.rollback()
        print("SEEDING ERROR:", e)

